English and Russian localization changes
TTT-2/TTTC pull request #22
Opened 2020-10-04 19:59 UTC by Satton2

• Russian localization improvements.
• I cannot test the addon properly (_no default classes_), but I guess "Reset" fits more here.
• Do you really need all these words to be started from capitals?

2020-10-06 11:33 UTC, TimGoll requested changes

2020-10-06 11:33 UTC, TimGoll commented on lua/terrortown/lang/deutsch/tttc.lua
> +local L = LANG.GetLanguageTableReference("Deutsch")
why did you change this to a capital letter? While both work, we use lowercase letters for the identifier.

2020-10-06 11:33 UTC, TimGoll commented on lua/terrortown/lang/english/tttc.lua
> +local L = LANG.GetLanguageTableReference("English")
same here

2020-10-06 11:33 UTC, TimGoll commented on lua/terrortown/lang/english/tttc.lua
> +L["ttt2_tttc_drop_class"] = "Reset class"
No, this is something completely different. "Remove Class" would be ok as well.

2020-10-20 19:51 UTC, Alf21 commented
@Satton2 just to check whether that's still alive

2020-10-20 22:02 UTC, Satton2 commented
> @Satton2 just to check whether that's still alive

Since I am alive, then this PR also alive. I just don't have time, sorry.

2021-01-03 15:11 UTC, closed without merging